Революция или эволюция? (часть 1)
htmlacademy-ecmascript/1353597-big-trip-14 pull request #5
Opened 2021-04-13 18:27 UTC by Sellywer

2021-04-14 22:58 UTC, dtsaryov requested changes

2021-04-14 22:58 UTC, dtsaryov commented on src/view/trip-sort.js
> +export default class Sorting {
https://up.htmlacademy.ru/ecmascript/14/criteries#b27

2021-04-14 22:58 UTC, dtsaryov commented on src/view/trip-sort.js
> +export default class Sorting {
Остальные места тоже проверь

2021-04-14 22:58 UTC, dtsaryov commented on src/main.js
> +const EMPTY_EVENTS_LIST = 0;
Ну уж такое можно в константу не выносить

2021-04-15 05:36 UTC, Sellywer commented on src/main.js
> +const EMPTY_EVENTS_LIST = 0;
Меня на прошлом курсе как раз ругали,если не выносила... короче 0 не нужно в константу?

2021-04-15 18:51 UTC, dtsaryov approved these changes

2021-04-15 18:51 UTC, dtsaryov commented on src/main.js
> +// ниже можно удалить
Если можно удалить - нужно удалить. Не держим закомментированный код

2021-04-15 18:51 UTC, merged